rundeck-plugins/kubernetes

contents/pods-read-logs.py
and make the `print` statement a little more python3 friendly too
=> Fix invalid container reference

contents/job-wait.py, plugin.yaml
The current k8s job create step does not wait for the
job to finish executing.
This new step allows waiting for job completion
and optionally reporting the k8s job logs.
Fixes #9
=> Add job waitfor step

contents/job-wait.py
This PR fixes  job-wait not detecting if the job has failed. Either if it has failed, completed, or reached max tries we do always attach the output for further debugging.
=> job-wait to detect when the job has failed

contents/common.py, contents/pods-copy-file.py
This should fix the script execution inside a pod not in 'default' namespace
=> Inline script step fails on Kubernetes pod node #38

contents/pods-wait.py
As the loop to wait for pod startup continues `while status == False` it would exit immidiately because the initial value is None. Set the initial value to False.
Maybe I'm overlooking something, but this fix worked for me.
=> pods-wait.py - Fixed initial value of status

contents/pods-run-script.py
failing when using "Kubernetes / Pods / Execute Script" while copying script into pod
> 	Traceback (most recent call last):
> 	  File "pods-run-script.py", line 156, in <module>
> 	    main()
> 	  File "pods-run-script.py", line 88, in main
> 	    destination_file_name=destination_file_name
> 	TypeError: copy_file() takes at least 6 arguments (5 given)
> 	Failed: NonZeroResultCode: Script result code was: 1
=> add namespace to script copy when using pod-run-script

contents/common.py
Fail step when exit code != 0
Step marked as OK even if exit code != 0
To check error, returned by kubernetes
Error checking code stealed from latest version of kubernetes-client/python-base:
https://github.com/kubernetes-client/python-base/blob/6b6546131217a2a9fdcf431a286c346619d2923a/stream/ws_client.py#L215
I'm not a python developer so code can be not perfect
May be it will be useful to add code like this in other connect_get_namespaced_pod_exec calls (like in run_command) but I not sure how to do it correctly
=> Get error from kubernetes response

contents/pods-resource-model.py
Problem:
node_set variable is empty
Not sure if this is a case for all the k8s clusters, but fixed my problem on EKS running kubernetes version 1.15
=> fix pod status filter

contents/job-create.py, plugin.yaml
allow adding all key-value pairs from configMap / secret to a job on creation (envFrom field)
=> Add envFrom to create job 

contents/common.py, contents/pods-resource-model.py
In node workflow steps, reuse authentication from pods-resource-model when per-step values are not specified
=> Reuse connection params from resource model in executor v2

contents/pods-copy-file.py, contents/pods-create.py, contents/pods-delete.py, contents/pods-node-executor.py, contents/pods-read-logs.py, contents/pods-run-script.py, contents/pods-wait.py, plugin.yaml
In many cases, the correct node information is (name and namespace) is in the node context. Use that instead of requiring users to manually enter the information. Preserve the ability to specify node manually, especially for the case where a pod is created at the beginning of a job with a specified name that will then flow through the entire workflow.
=> Use node information for pod commands when fields are left unspecified

contents/job-create.py, plugin.yaml
There is a bug when you want to apply `node_selector` for the `job/create` workflow.
I fixed it in this PR.
=> fixed node selector bug in Job / Create workflow

contents/job-create.py
In order to limit right access to job, we can use serviceaccount.
=> Allow to launch a job with a serviceaccount

contents/common.py
The indents in the current code do not correspond to the python k8s API and make the code subject to failure if type is not specified in the YAML. But I think the data maps to https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1HostPathVolumeSource.md whihc says type is optional.
On that basis, I think volume.host_paath should be set whether or not a type is specified and the code should not fail if a type is unspecified.
=> possibly incorrect indents in create_volume() in common.py

contents/job-wait.py, contents/pods-read-logs.py
If there is a non ascii char, the plugin breaks with the error below and fails the rundeck job.
this fix will skip the print of the char, but probably most of the log will still be usable and its better than current behaviour.
in my case it was the char µ, but it can happen with other chars too.
```Traceback (most recent call last):
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-2.0.5-SNAPSHOT/job-wait.py", line 148, in <module>
main()
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-2.0.5-SNAPSHOT/job-wait.py", line 144, in main
wait()
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-2.0.5-SNAPSHOT/job-wait.py", line 111, in wait
print(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 11568: ordinal not in range(128)
Failed: …
```
=> Ignore non ascii chars that cant be encoded for prints

contents/common.py, contents/deployment-update.py, contents/job-create.py
Strip strings of container commands before splitting by whitespace.
A trailing whitespace will result an extra empty argument which will then be parsed to a newline on the pod yaml and prevent the container from getting its arguments (if provided from the container args field).
A leading whitespace will result in the command itself being parsed as an argument.
ps.
I remove trailing whitespace on save, so the PR include some cleanups of unrelated code.
=> Strip before splitting by space

README.md, contents/pods-resource-model.py, plugin.yaml
Ticket: https://pagerduty.atlassian.net/browse/RSE-250
Can not load node sources when using a token for a user that has access to only specific namespaces.
Include a field "Namespace" among the other "Config" fields:
________
These 2 values would be equivalent:
The difference is that using field selector you will get an error if you don't have permissions to access other namespaces, because it will load all pods from any namespace and after that it will apply the selector.
=> RSE-250: get pods on authorized namespace

contents/job-delete.py, contents/job-wait.py
IMO, when using k8s in the rundeck environment, you probably have limited role. Therefore, you should call k8s API which requires minimal role
* read_namespaced_job_status -> read_namespaced_job
read_namespaced_job_status needs  role `API group "batch", resource "jobs/status", verbs: "get" in its namespace`
read_namespaced_job needs  role `API group "batch", resource "jobs", verbs: "get" in its namespace`
there is no essential difference
* list_pod_for_all_namespaces -> list_namespaced_pod
list_pod_for_all_namespaces needs role `API group "", resource "pods", verbs: "list" in cluster scope`
list_namespaced_pod needs role `API group "", resource "pods", verbs: "list" in its namespace`
---
* Change print to use logger
- I think this repo needs lint rules
=> feat(job-delete, job-wait): Change k8s method in job scripts considering RBAC

contents/create-from-yaml.py, plugin.yaml
Needed to be able to spin pods with service accounts on GKE (needed for workload identity), and `stdin:true` and `tty:true` options set. That way I can execute arbitrary scripts into them. :+1:
=> Added support for freeform pods

plugin.yaml
Simple fix to properly mount volumes on ephemeral pods
=> Aligned volume_mounts specification for 'Kubernetes-Create-Pod'

contents/delete.py
Rundeck were unable to delete an ingress with the plugin.
Deprecation of: 'ExtensionsV1beta1Api()'
Usage of ''NetworkingV1Api()"
[Python Client](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/NetworkingV1Api.md#delete_namespaced_ingress)
=> RSE-291: Cannot Delete Ingress with Kubernetes Plugin

plugin.yaml
Backend logic already existed to accept the container property, but the property simply hadn't been added to the "Pod / Execute Command" workflow step. 
Unsure why tests are failing.  Plugin works as expected: specifying the container (within the same pod) executes the command in the desired container.
=> Add "container" property to Execute Command workflow step

contents/debug-ephemeral-container.py, plugin.yaml
Please conduct a code-review of the plugin.  This plugin adds an ephemeral container to an existing (running) pod so that debugging utilities can be used to investigate the other containers in that pod.  
Documentation for this feature can be found [here](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container).
=> RUN-1525: Add plugin for Ephemeral Debug Container
