plugin.yaml

* added `config_file` entry to each Workflow step to fix issue #5 
* removed EOL whitepace (because I'm a bit OCD)

allow the use of kubeconfig file in all Workflow Steps

---

contents/common.py
contents/create-from-yaml.py
contents/delete.py
contents/deployment-create.py
contents/deployment-delete.py
contents/deployment-status.py
contents/deployment-update.py
contents/deployment-wait.py
contents/job-create.py
contents/job-delete.py
contents/job-run.py
contents/service-create.py
contents/service-delete.py
contents/service-update.py

for https://github.com/rundeck-plugins/kubernetes/issues/13

Fixing output data

---

contents/common.py
contents/pods-copy-file.py
contents/pods-create.py
contents/pods-delete.py
contents/pods-node-executor.py
contents/pods-run-script.py
contents/pods-wait.py
plugin.yaml

New pods steps:
- Create Pod
- Delete Pod
- Wait for Pod
- Run script on Pod
- Run command on Pod

New pods steps

---

contents/common.py
plugin.yaml

New types for container volumes:
* secret
* configMap

Adds secret and configMap as volumes sources

---

contents/job-create.py
plugin.yaml

Add Annotations to Job Create + make pod inherit Labels and Annotations

---

contents/job-create.py
plugin.yaml

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy

Adds backoff_limit to Job

---

build.gradle
contents/StatefulSet-wait.py
contents/common.py
contents/delete.py
contents/deployment-create.py
contents/deployment-wait.py
contents/pods-copy-file.py
contents/pods-resource-model.py
plugin.yaml

- support python3
- adding annotations to deployments
- changing format for volumenMounts on deployments (using yaml formate instead key/value)

new features for 1.0.12

---

plugin.yaml

Fix delete pod description

---

contents/common.py
contents/create-from-yaml.py
contents/job-create.py

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
Please check if yaml.full_load is needed.

fix deprecated yaml.load

---

contents/delete.py

bug fix :
AttributeError: 'ExtensionsV1beta1Api' object has no attribute 'delete_namespaced_stateful_set'
--
delete generic statefulset in a specific namespace.

Update delete.py  [ bug fix 	AttributeError: 'ExtensionsV1beta1Api' object has no attribute 'delete_namespaced_stateful_set' "

---

contents/common.py
contents/deployment-create.py
contents/job-create.py
contents/job-wait.py
contents/pods-create.py
plugin.yaml

for https://github.com/rundeck-plugins/kubernetes/issues/34

adding image pull secret

---

contents/common.py
contents/job-create.py
plugin.yaml

Support for two more configurations (to allow usage of preemtible nodes) for jobs created through the plugin.
ps. 
I remove trailing whitespace on save, so the PR include some cleanups of unrelated code.

Add Node selectors and Tolerations to create job

---

README.md
contents/common.py
contents/pods-copy-file.py
contents/pods-create.py
contents/pods-delete.py
contents/pods-node-executor.py
contents/pods-run-script.py

Fixes deprecated classpath in python kube api lib.

Fixdeprecatedapi

---

plugin.yaml

for issue https://github.com/rundeck-plugins/kubernetes/issues/63

container ports optional

---

.github/workflows/gradle.yml
.github/workflows/release.yml
contents/job-wait.py
contents/pods-read-logs.py
plugin.yaml

for issue https://github.com/rundeck-plugins/kubernetes/issues/58

live output for logs

---

contents/pods-resource-model.py
plugin.yaml

for issue https://github.com/rundeck-plugins/kubernetes/issues/41

add label selector

---

contents/common.py
contents/create-from-yaml.py
contents/delete.py
contents/deployment-create.py
contents/deployment-delete.py
contents/deployment-status.py
contents/deployment-update.py
contents/deployment-wait.py
contents/job-create.py
contents/job-wait.py
contents/pods-resource-model.py
plugin.yaml

Removing beta API's and fixing some issues.
fixing issues:
- https://github.com/rundeck-plugins/kubernetes/issues/70
- https://github.com/rundeck-plugins/kubernetes/issues/65
- https://github.com/rundeck-plugins/kubernetes/issues/71

removing beta apis

---

contents/common.py

for issue https://github.com/rundeck-plugins/kubernetes/issues/4

fix issue with assert_hostname

---

contents/pods-resource-model.py

Seems ok for me but i'm really new to python, rundeck plugins and kubernetes

evicted pods do not have status

---

README.md
build.gradle
contents/StatefulSet-wait.py
contents/common.py
contents/deployment-create.py
contents/deployment-update.py
contents/deployment-wait.py
contents/job-create.py
contents/pods-copy-file.py
contents/pods-create.py
contents/pods-node-executor.py
contents/pods-run-script.py
contents/pods-wait.py
examples/Deploy-NGINX.xml
plugin.yaml

This PR fixes a number of spelling errors I found in the code. In a couple of places there were corresponding grammatical errors I fixed.
It also removes the trailing period from two log messages since in all other places your log messages do not have them.

Fix spelling errors

---

plugin.yaml

for https://github.com/rundeck-plugins/kubernetes/issues/109

disable emoticons by default

---

contents/job-wait.py

In my case, the nodes in k8s cluster are autoscaling by demand of jobs, the instance takes avg 5 min to be ready.
When some job start a new machine, rundeck don´t follow the log because the first loop set the var `show_log = False` in the line [119](https://github.com/rundeck-plugins/kubernetes/blob/master/contents/job-wait.py#L119), then the next loop ignore the log and follow counting the retries but the job is running inside k8s. When finished the counting, the job is failed but still running in the cluster
```sh
INFO: kubernetes-wait-job: Fetching logs from pod: test-env-qxtkt
INFO: kubernetes-wait-job: ========================== job log start ==========================
INFO: kubernetes-wait-job: =========================== job log end ===========================
INFO: …
```

Watch Log interrupted job-wait.py

---

.github/workflows/gradle.yml
.github/workflows/release.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

match the artifact name with the repo name

Upgrade archive name

---

contents/pod-describe.py
plugin.yaml

This is a node-step plugin that will describe the specified pod (or pods).  Like other node-step plugins for pods, users can place their specified pod in the Property/Field, or they can use `dispatch to nodes` and leave the field blank.

Add Describe-Pod plugin

---

.github/workflows/tests.yml
.gitignore
README.md
contents/common.py
contents/deployment-update.py
contents/pods-resource-model.py
plugin.yaml
tox.ini

- Fixed resource model assembly for k8s pods lacking labels
- Added handling for unspecified ports at the pods creating flow
- Refactored k8s lib beta function used in the deployment update flow
- Dropped support for python2

RUN-2676 : Overhaul
